# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python App

on: 

workflow_dispatch:
    branches:    
      - 'main'
jobs:
  build:   
    runs-on: ubuntu-latest  
    steps:
        - name: checkout actions
          uses: actions/checkout@v3

        - name: Set up Python 3.7
          uses: actions/setup-python@v3
          with:
            python-version: '3.x'

        - name: Update paper list
          run: |
            python main.py

        - name: commit
          run: |
            git add .
            git commit -m "update" -a

