# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python App

on:
  release:    
  
  workflow_dispatch:
  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Display Python version
      run: python --version
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install jinja2 -i 
          
    - name: build app    
      run: python main.py
    
    - name: Commit files
      run:
        git add .
        git commit -m "update" -a
