# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python App

on:
  schedule:
    - cron: '59 05 * * *'
  workflow_dispatch:
  
jobs:
 build_App_and_Push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Display Python version
      run: python --version
      
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install jinja2 
          pip install requests          
          pip install lxml
          
    - name: build app    
      run: python main-githubaction.py
    
    - name: Commit files
      run: |
          git config --local user.email "postaaa@gmail.com"
          git config --local user.name "Sean"
          git add .
          git commit -m "update daily data on date." #动态提交信息
      # 推送到github仓库
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: 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
        branch: main        
 
    - name: Deploy
      id: deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_TREE_02B6D5410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "scr" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: "true"
          ###### End of Repository/Build Configurations ######
